//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public string CharacterName { get; set; }
        public string CharacterDescription { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
